# http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/sample-templates-services-us-west-2.html#w1ab2c21c45c15c15
# Amazon EC2 instance in a security group Creates an Amazon EC2 instance in an Amazon EC2 security group.
---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
#  CloudformationKeyName:
#    Type: String
  VpcId:
    Type: String
    Default: vpc-9b992ff1
  AvailabilityZones:
    Type: AWS::EC2::AvailabilityZone::Name
    Default:
      eu-central-1a
    AllowedValues:
    - eu-central-1a
    - eu-central-1b
    - eu-central-1c
  ImageIdUbuntu:
    Type: AWS::EC2::Image::Id
    Default:  ami-0c960b947cbb2dd16
  ImageIdWindows:
    Type: AWS::EC2::Image::Id
    Default: ami-0da198ce94f235cdc
  InstanceType:
    Type: String
    Default:  t2.micro
  LaunchTemplateUrl:
    Type: String
    Default:  https://templates-cmdrunematti.s3.eu-central-1.amazonaws.com/templates/InstanceWithSecurity.cf
Resources:
  UbuntuNginx:
     Type: AWS::CloudFormation::Stack
     Properties: 
       TemplateURL: !Ref LaunchTemplateUrl
       Parameters: 
         UserDataParameter:
           !Base64 |
             #!/bin/bash
             sudo apt update 
             sudo apt install apache2 -y 
             sudo systemctl restart apache2
         ImageIdParameter: !Ref ImageIdUbuntu
         InstanceTypeParameter: !Ref InstanceType
         VpcIdParameter: !Ref VpcId
         LoadBalancerNameParameter: !Ref LoadBalancer
  UbuntuApache:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: !Ref LaunchTemplateUrl
      Parameters: 
        UserDataParameter: 
          !Base64 |
            #!/bin/bash
            sudo apt update 
            sudo apt install nginx -y
            sudo systemctl restart nginx
        ImageIdParameter: !Ref ImageIdUbuntu
        InstanceTypeParameter: !Ref InstanceType 
        VpcIdParameter: !Ref VpcId
        LoadBalancerNameParameter: !Ref LoadBalancer
  WindowsServer:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: !Ref LaunchTemplateUrl
      Parameters: 
        UserDataParameter:
          !Base64 |
            <powershell>
            Install-WindowsFeature -name Web-Server -IncludeManagementTools
            </powershell>
        ImageIdParameter: !Ref ImageIdWindows
        InstanceTypeParameter: !Ref InstanceType
        VpcIdParameter: !Ref VpcId
        LoadBalancerNameParameter: !Ref LoadBalancer
  LoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      AvailabilityZones:
        - !Ref AvailabilityZones
      CrossZone: true
      Instances:
      - !GetAtt UbuntuNginx.Outputs.InstanceName
      - !GetAtt UbuntuApache.Outputs.InstanceName
      - !GetAtt WindowsServer.Outputs.InstanceName
      Listeners:
      - InstancePort: '80'
        LoadBalancerPort: '80'
        Protocol: HTTP
